### ISSUE TITLE
Is svelterialjs dead ?

### ISSUE THREAD

**Issue by lloyet** [svelterialjs/svelterial#6]
Since last july, i can not see any news from @TheComputerM about this new UI.
Do you think new contents are going to be publish ?

**Comment by TheComputerM** [comment]
Actually I did not get good enough marks for my exams so I am repeating, they will be over in the next four months. I will get started on updating svelterial when I will be free. Also looking to inherit principles from material you.

**Comment by bradms** [comment]
Take your time, @TheComputerM. While I am greatly excited for this, your health is much more important than some UI components.

**Comment by lloyet** [comment]
> Actually I did not get good enough marks for my exams so I am repeating, they will be over in the next four months. I will get started on updating svelterial when I will be free. Also looking to inherit principles from material you.

Good luck for your new exams. Material You sounds implement a new way to perform component, good idea !

**Comment by robots4life** [comment]
All the best with your exams. While at it keep in good health.
Please update us all on... your exams of course ! :muscle:
Good luck ! :+1:

**Comment by TheComputerM** [comment]
https://github.com/svelterialjs/svelterial/issues/3#issuecomment-1240224395

Btw exams went great, they were also delayed hence I could not come back sooner.
